@OpenFGADemo_HostAddress = https://localhost:7069

GET {{OpenFGADemo_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{OpenFGADemo_HostAddress}}/documents/list-store
Accept: application/json


###
# Bu modelin oluşturulması için kullandığımız endpoint

PUT https://localhost:7069/Documents/create




###


POST {{OpenFGADemo_HostAddress}}/documents/assign?userId=alper&documentId=DDD.pdf&permission=owner
Accept: application/json


###


POST {{OpenFGADemo_HostAddress}}/documents/assign?userId=ali&documentId=DDD.pdf&permission=reader
Accept: application/json


###


POST {{OpenFGADemo_HostAddress}}/documents/assign?userId=veli&documentId=DDD.pdf&permission=writer
Accept: application/json






###


POST {{OpenFGADemo_HostAddress}}/documents/check
Accept: application/json
Content-Type: application/json

{
  "userId":"veli",
  "documentId":"DDD.pdf",
  "permission":"reader"
}






###
# Demo Get metodunun çağırımı / Admin kullanıcısı için

GET {{OpenFGADemo_HostAddress}}/Demo
Accept: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=


###
# Demo Get metodunun çağırımı / Alper kullanıcısı için

GET {{OpenFGADemo_HostAddress}}/Demo
Accept: application/json
Authorization: Basic YWxwZXI6cGFzc3dvcmQ=



###


POST {{OpenFGADemo_HostAddress}}/documents/assign?userId=admin&documentId=DemoWebApi&permission=owner
Accept: application/json




###
# Demo/Demo Get metodunun çağırımı / Admin kullanıcısı için

GET {{OpenFGADemo_HostAddress}}/Demo/Demo
Accept: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

